#!/usr/bin/env python3
"""
Rasterize a TTF to 5-column × 8-row glyphs for PCD8544 (see pcd8544.c).

Column bytes: bit y set => pixel on at row y within the 8-pixel band (bit 0 = top).

Usage (from this directory; output goes to repo-root tools/):
  python ttf_to_pcd8544_font.py --ttf path/to/font.ttf --out-c ../../../../tools/custom_fixed_pcd8544.c
"""
from __future__ import annotations

import argparse
import os
import sys

try:
    from PIL import Image, ImageDraw, ImageFont
except ImportError as e:
    print("Requires Pillow: pip install Pillow", file=sys.stderr)
    raise SystemExit(1) from e

FIRST = 0x20
LAST = 0x7E
COUNT = LAST - FIRST + 1
CELL_W = 5
CELL_H = 8  # one PCD8544 row band


def ink_bbox(im: Image.Image, thresh: int = 128) -> tuple[int, int, int, int] | None:
    """Bounding box of pixels darker than thresh (L mode: background is 255)."""
    px = im.load()
    w, h = im.size
    min_x, min_y = w, h
    max_x, max_y = -1, -1
    for y in range(h):
        for x in range(w):
            v = px[x, y]
            if isinstance(v, tuple):
                v = v[0]
            if v < thresh:
                if x < min_x:
                    min_x = x
                if y < min_y:
                    min_y = y
                if x > max_x:
                    max_x = x
                if y > max_y:
                    max_y = y
    if max_x < 0:
        return None
    return (min_x, min_y, max_x + 1, max_y + 1)


def glyph_to_columns(im: Image.Image) -> list[int]:
    w, h = im.size
    if w != CELL_W or h != CELL_H:
        raise ValueError(f"expected {CELL_W}x{CELL_H}, got {w}x{h}")
    cols: list[int] = []
    px = im.load()
    for x in range(CELL_W):
        b = 0
        for y in range(CELL_H):
            v = px[x, y]
            if isinstance(v, tuple):
                v = v[0]
            if v < 128:
                b |= 1 << y
        cols.append(b)
    return cols


def render_char(font: ImageFont.FreeTypeFont, ch: str) -> list[int]:
    """Draw one character into CELL_W x CELL_H, thresholded (black on white)."""
    if ch.isspace() and ch != " ":
        return [0] * CELL_W

    scratch = Image.new("L", (48, 32), 255)
    dr = ImageDraw.Draw(scratch)
    bx = dr.textbbox((0, 0), ch, font=font)
    pad = 4
    ox = pad - bx[0]
    oy = pad - bx[1]
    dr.text((ox, oy), ch, font=font, fill=0)

    bbox = ink_bbox(scratch)
    if bbox is None:
        return [0] * CELL_W

    ink = scratch.crop(bbox)
    iw, ih = ink.size
    if iw < 1 or ih < 1:
        return [0] * CELL_W

    scale = min((CELL_W - 1) / iw, (CELL_H - 1) / ih) * 0.95
    nw = max(1, int(iw * scale))
    nh = max(1, int(ih * scale))
    ink = ink.resize((nw, nh), Image.Resampling.LANCZOS)

    out = Image.new("L", (CELL_W, CELL_H), 255)
    px = ((CELL_W - nw) // 2, (CELL_H - nh) // 2)
    out.paste(ink, px)
    return glyph_to_columns(out)


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--ttf", required=True, help="Path to .ttf")
    ap.add_argument("--out-c", required=True, help="Output .c path")
    ap.add_argument("--out-h", help="Output .h path (default: alongside .c)")
    ap.add_argument("--name", default="pcd8544_font_glyphs", help="C symbol base name")
    ap.add_argument("--font-px", type=int, default=11, help="PIL font size (tune legibility on 5x8)")
    args = ap.parse_args()

    if not os.path.isfile(args.ttf):
        print(f"not found: {args.ttf}", file=sys.stderr)
        raise SystemExit(1)

    font = ImageFont.truetype(args.ttf, args.font_px)

    table: list[list[int]] = []
    for code in range(FIRST, LAST + 1):
        ch = chr(code)
        cols = render_char(font, ch)
        table.append(cols)

    out_h = args.out_h
    if not out_h:
        base, _ = os.path.splitext(args.out_c)
        out_h = base + ".h"

    os.makedirs(os.path.dirname(os.path.abspath(args.out_c)) or ".", exist_ok=True)

    guard = "PCD8544_FONT_DATA_H"
    with open(out_h, "w", encoding="utf-8") as fh:
        fh.write("/* Generated by ttf_to_pcd8544_font.py — do not edit by hand. */\n")
        fh.write(f"#ifndef {guard}\n#define {guard}\n\n")
        fh.write("#include <stdint.h>\n\n")
        fh.write(f"#define PCD8544_FONT_FIRST 0x{FIRST:02X}\n")
        fh.write(f"#define PCD8544_FONT_LAST  0x{LAST:02X}\n")
        fh.write(f"#define PCD8544_FONT_COUNT {COUNT}\n")
        fh.write(f"#define PCD8544_FONT_COL_BYTES {CELL_W}\n\n")
        fh.write(f"extern const uint8_t {args.name}[PCD8544_FONT_COUNT][PCD8544_FONT_COL_BYTES];\n\n")
        fh.write(f"#endif /* {guard} */\n")

    with open(args.out_c, "w", encoding="utf-8") as fc:
        fc.write("/* Generated by ttf_to_pcd8544_font.py — do not edit by hand. */\n")
        fc.write('#include "custom_fixed_pcd8544.h"\n\n')
        fc.write(
            f"const uint8_t {args.name}[PCD8544_FONT_COUNT][PCD8544_FONT_COL_BYTES] = {{\n"
        )
        for i, cols in enumerate(table):
            ch = chr(FIRST + i)
            esc = ch.replace("\\", "\\\\").replace("'", "\\'")
            cstr = ", ".join(f"0x{b:02X}" for b in cols)
            fc.write(f"  {{ {cstr} }}, /* {esc} */\n")
        fc.write("};\n")

    print(f"Wrote {args.out_c}\n{out_h}")


if __name__ == "__main__":
    main()
