import freetype

FONT_PATH = "ByteBounce.ttf"
OUTPUT_C = "ByteBounce_16.c"
OUTPUT_H = "ByteBounce_16.h"

FIRST_CHAR = 32
LAST_CHAR = 126
FONT_HEIGHT = 16

face = freetype.Face(FONT_PATH)
face.set_pixel_sizes(0, FONT_HEIGHT)

bitmaps = []
offsets = []
offset = 0


def sample_px(bitmap, x, y, pitch):
    """Grayscale bitmap: one byte per pixel; `pitch` bytes per row (not always width)."""
    return bitmap.buffer[y * pitch + x]


for char_code in range(FIRST_CHAR, LAST_CHAR + 1):
    face.load_char(chr(char_code), freetype.FT_LOAD_RENDER)
    glyph = face.glyph
    bitmap = glyph.bitmap

    width = bitmap.width
    rows = bitmap.rows
    pitch = bitmap.pitch
    if pitch < 0:
        pitch = -pitch

    if width == 0 or rows == 0:
        offsets.append(offset)
        bitmaps.append([0])
        offset += 1
        continue

    ymin = rows
    ymax = -1
    for y in range(rows):
        for x in range(width):
            if sample_px(bitmap, x, y, pitch) > 0:
                ymin = min(ymin, y)
                ymax = max(ymax, y)

    if ymax < 0:
        offsets.append(offset)
        bitmaps.append([0])
        offset += 1
        continue

    cols = []

    for x in range(width):
        col_low = 0
        col_high = 0
        for y in range(ymin, ymax + 1):
            new_y = y - ymin
            if new_y >= FONT_HEIGHT:
                break
            if sample_px(bitmap, x, y, pitch) > 0:
                if new_y < 8:
                    col_low |= 1 << new_y
                else:
                    col_high |= 1 << (new_y - 8)

        cols.append(col_low)
        cols.append(col_high)

    offsets.append(offset)
    bitmaps.append([width] + cols)
    offset += 1 + len(cols)

# Write .c
with open(OUTPUT_C, "w") as f:
    f.write('#include "ByteBounce_16.h"\n\n')

    f.write("const uint8_t ByteBounce16_Bitmaps[] = {\n")
    for glyph in bitmaps:
        f.write("  " + ", ".join(f"0x{b:02X}" for b in glyph) + ",\n")
    f.write("};\n\n")

    f.write("const uint16_t ByteBounce16_Offsets[] = {\n")
    f.write("  " + ", ".join(str(o) for o in offsets))
    f.write("\n};\n")

# Write .h
with open(OUTPUT_H, "w") as f:
    f.write("#ifndef BYTEBOUNCE16_H\n#define BYTEBOUNCE16_H\n\n")
    f.write("#include <stdint.h>\n\n")
    f.write(f"#define BYTEBOUNCE_FIRST_CHAR {FIRST_CHAR}\n")
    f.write(f"#define BYTEBOUNCE_LAST_CHAR {LAST_CHAR}\n")
    f.write(f"#define BYTEBOUNCE_HEIGHT {FONT_HEIGHT}\n\n")
    f.write("extern const uint8_t ByteBounce16_Bitmaps[];\n")
    f.write("extern const uint16_t ByteBounce16_Offsets[];\n\n")
    f.write("#endif\n")

print("DONE: Generated ByteBounce_16.c and ByteBounce_16.h")
