#!/usr/bin/env python3
"""
Convert raw/wirelessMeter.png (84x48) to PCD8544 band buffers for ui/sb1_wireless_meter.h.

- sb1_wireless_meter: full image (T + signal bars when BT or Wi‑Fi is up)
- sb1_wireless_meter_bg: idle state — **T shape only**; ink with y < T_KEEP_MIN_Y is cleared (signal bars
  above the T). Tune METER_BARS_MAX_Y if the art changes.

Run from repo root:
  python tools/png_to_sb1_wireless_meter.py

Requires Pillow.
"""
from __future__ import annotations

import os
import sys

try:
    from PIL import Image
except ImportError as e:
    print("Requires Pillow: pip install Pillow", file=sys.stderr)
    raise SystemExit(1) from e

W, H = 84, 48
THRESH = 128
# Idle keeps only the T glyph; rows above (signal ladder + narrow connector stem) are cleared.
# Current raw/wirelessMeter.png: ladder/connector y≈5–38; T crossbar y=39, stem y=40–42.
T_KEEP_MIN_Y = 39


def image_to_bands(im_l: Image.Image) -> list[int]:
    px = im_l.load()
    out: list[int] = []
    for bank in range(6):
        for x in range(W):
            b = 0
            for bit in range(8):
                y = bank * 8 + bit
                if y >= H:
                    continue
                if px[x, y] < THRESH:
                    b |= 1 << bit
            out.append(b)
    assert len(out) == 504
    return out


def format_c_array(name: str, data: list[int]) -> str:
    lines = []
    for i in range(0, 504, 12):
        chunk = data[i : i + 12]
        lines.append("    " + ", ".join(f"0x{b:02x}" for b in chunk) + ",")
    lines[-1] = lines[-1].rstrip(",")
    return f"static const uint8_t {name}[504] = {{\n" + "\n".join(lines) + "\n};"


def main() -> None:
    repo = os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))
    png_path = os.path.join(repo, "raw", "wirelessMeter.png")
    out_path = os.path.join(repo, "ui", "sb1_wireless_meter.h")

    im = Image.open(png_path).convert("L")
    if im.size != (W, H):
        print(f"Expected {W}x{H}, got {im.size}", file=sys.stderr)
        raise SystemExit(1)

    full_bands = image_to_bands(im)

    px = im.load()
    bg_im = im.copy()
    bg_px = bg_im.load()
    cleared = 0
    for y in range(min(T_KEEP_MIN_Y, H)):
        for x in range(W):
            v = bg_px[x, y]
            if isinstance(v, tuple):
                v = v[0]
            if v < THRESH:
                bg_px[x, y] = 255
                cleared += 1
    bg_bands = image_to_bands(bg_im)

    hdr = f"""#ifndef SB1_WIRELESS_METER_H
#define SB1_WIRELESS_METER_H

#include <stdint.h>

/* Generated by tools/png_to_sb1_wireless_meter.py from raw/wirelessMeter.png */
/* PCD8544: 504 bytes, 84 cols x 6 bands, bit0 = top pixel in band; black = 1 */

/* Full frame (bars visible when firmware chooses sb1_wireless_meter). */
{format_c_array("sb1_wireless_meter", full_bands)}

/* Idle: T shape only (rows y>={T_KEEP_MIN_Y} ink); upper signal bars cleared. */
{format_c_array("sb1_wireless_meter_bg", bg_bands)}

#endif
"""

    with open(out_path, "w", encoding="utf-8") as f:
        f.write(hdr)

    print(f"Wrote {out_path}")
    print(f"  idle bg: cleared {cleared} dark pixels with y < {T_KEEP_MIN_Y} (signal bars); kept y >= {T_KEEP_MIN_Y} (T)")


if __name__ == "__main__":
    main()
