#!/usr/bin/env python3
"""
Convert raw/livemodeButtons.png (84x48) to PCD8544 band buffer for ui/sb1_livemode_buttons.h

Run from repo root:
  python tools/png_to_sb1_livemode_buttons.py

Requires Pillow.
"""
from __future__ import annotations

import os
import sys

try:
    from PIL import Image
except ImportError as e:
    print("Requires Pillow: pip install Pillow", file=sys.stderr)
    raise SystemExit(1) from e

W, H = 84, 48
THRESH = 128


def image_to_bands(im_l: Image.Image) -> list[int]:
    px = im_l.load()
    out: list[int] = []
    for bank in range(6):
        for x in range(W):
            b = 0
            for bit in range(8):
                y = bank * 8 + bit
                if y >= H:
                    continue
                if px[x, y] < THRESH:
                    b |= 1 << bit
            out.append(b)
    assert len(out) == 504
    return out


def format_c_array(name: str, data: list[int]) -> str:
    lines = []
    for i in range(0, 504, 12):
        chunk = data[i : i + 12]
        lines.append("    " + ", ".join(f"0x{b:02x}" for b in chunk) + ",")
    lines[-1] = lines[-1].rstrip(",")
    return f"static const uint8_t {name}[504] = {{\n" + "\n".join(lines) + "\n};"


def main() -> None:
    repo = os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))
    png_path = os.path.join(repo, "raw", "livemodeButtons.png")
    out_path = os.path.join(repo, "ui", "sb1_livemode_buttons.h")

    im = Image.open(png_path).convert("L")
    if im.size != (W, H):
        print(f"Expected {W}x{H}, got {im.size}", file=sys.stderr)
        raise SystemExit(1)

    bands = image_to_bands(im)

    hdr = f"""#ifndef SB1_LIVEMODE_BUTTONS_H
#define SB1_LIVEMODE_BUTTONS_H

#include <stdint.h>

/* Generated by tools/png_to_sb1_livemode_buttons.py from raw/livemodeButtons.png */
/* PCD8544: 504 bytes, 84 cols x 6 bands, bit0 = top pixel in band; black = 1 */

{format_c_array("sb1_livemode_buttons", bands)}

#endif
"""

    with open(out_path, "w", encoding="utf-8") as f:
        f.write(hdr)

    print(f"Wrote {out_path}")


if __name__ == "__main__":
    main()
